### ISSUE TITLE
dumdata_one command allows to choose among different databases

### ISSUE THREAD

**Issue by alv-around** [ascaliaio/django-dumpdata-one#4]
Hello,

I find your plugin very helpful. However for my purpose have multiple databases in my application and what to specify which one to dump the data from.

I tried making a PR to support the feature, but I am not allowed to push my own branch.

I also don't see any CONTRIBUTING guidelines, or any documentation on how to run the tests. But is that maybe the topic for another issue ? 🙃 

I would be happy to help. Cheers

**Comment by Ylodi** [comment]
Hello,

currently, there are no contribution guidelines but I will add them in future (that can be another issue).

Can You create a pull request (from a fork) as described in the documentation? 

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

I'm glad you find the plugin useful and want to help. :-)

**Comment by alv-around** [comment]
Ok, cool. I didn't know you can PR from a forked repo.

I just pushed the [PR](https://github.com/ascaliaio/django-dumpdata-one/pull/5). But I haven't write tests for it. I am not sure on how to get the tests running.

Looking forward for your feedback :)

**Comment by Ylodi** [comment]
Thank you for your contribution.

P.S. Sorry for the delay.
