### ISSUE TITLE
Filter by date range

### ISSUE THREAD

**Issue by pije76** [ascaliaio/django-dumpdata-one#6]
Great package!
I love your package, it is very helpful.
Can I use filter by date range? Example from 2020-01-01 to 2020-12-31 ?

**Comment by Ylodi** [comment]
Yes, suppose the date field is called created_at...

`--filter=created_at__gte=2020-01-01,created_at__lte=2020-12-31`

**Comment by pije76** [comment]
Greaaat!
Thank you so much @Ylodi
